# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laura Rocha Prado
email: laura@rochaprado.com
description: I'm a crafty scientist who loves to code.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site
github_username: arbolitoloco
twitter_username: laurarochaprado

markdown: kramdown
permalink: pretty
paginate: 12

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  laura:
    name: Laura Rocha Prado
    bio: Biodiversity Informatician at Arizona State University. Leaf beetle specialist. Full-stack developer trying all web things. Craft-a-holic.
    gravatar: https://en.gravatar.com/userimage/14726990/29c5a817483c1fe9db0ef9f9c9ff1023.jpeg
    email: laura@rochaprado.com
    website: https://laura.rochaprado.com/
    github_username: arbolitoloco
    twitter_username: arbolitoloco
